retrieve jsonfeed data
blockchainworkbench/workbench-ui pull request #8
Opened 2018-12-17 23:11 UTC by severus-sn4pe

initial implementation of retrieve data #4 with `redux-saga`

2018-12-18 16:00 UTC, thibmeu requested changes
Some modifications to perform before merging.
Addition are great

2018-12-18 16:00 UTC, thibmeu commented on README.md
> -This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
Why removing content from this file?
I think it is still relevant.

2018-12-18 16:00 UTC, thibmeu commented on src/components/layout/LoadingIndicator.js
> +            ? <p className='loading'><img src='/loading.gif' alt='' className='image is-30x30'/></p> : '');
What about using `fa fa-spinner fa-spin` instead? It is pure css and font-awesome is already included.

2018-12-18 16:00 UTC, thibmeu commented on src/components/search/PageList.js
>          const rows = _.chunk(this.props.pages, 3);
For this code, it would be better to use `flexbox` to do the work without requiering javascript rendering.
I would advice you to have a look https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2018-12-18 16:00 UTC, thibmeu commented on src/components/search/PageList.js
> +        for (let row of rows.entries()) {
When you have flexbox in place, this becomes:
```javascript
content = rows.map((value, index) => 
  <div key={index} className='tile is-ancestor'>
    {value.map(page=> ....)}
  </div>
)
```

2018-12-18 16:00 UTC, thibmeu commented on src/components/search/PageList.js
> +    return getVisiblePagesByCategories(pages, categories, categoryFilterType);
Why don't you use `difficulty` anymore?

2018-12-18 16:00 UTC, thibmeu commented on src/components/search/PageListItem.js
> +                                className="title is-4">{this.props.page ? this.props.page.title : '??'}</span>
`Page undefined` is clearer to me.

2018-12-19 09:22 UTC, severus-sn4pe commented on src/components/layout/LoadingIndicator.js
> +            ? <p className='loading'><img src='/loading.gif' alt='' className='image is-30x30'/></p> : '');
yes, that is better, will change that

2018-12-20 14:01 UTC, severus-sn4pe commented on src/components/search/PageListItem.js
> +                                className="title is-4">{this.props.page ? this.props.page.title : '??'}</span>
fixed

2018-12-20 14:02 UTC, severus-sn4pe commented on src/components/search/PageList.js
> +    return getVisiblePagesByCategories(pages, categories, categoryFilterType);
I have added it again

2018-12-20 14:03 UTC, severus-sn4pe commented on src/components/search/PageList.js
> +        for (let row of rows.entries()) {
I now use `columns` and `is-multiline` for flexbox.

2018-12-20 14:14 UTC, severus-sn4pe commented
I've added a `.env` file with `REACT_APP_JSONFEED_BASE` currently set to `https://raw.githubusercontent.com/severus-sn4pe/jsonfeed/demo-content/docs/` for testing, as I didn't push the jsonfeed to the organization repository yet.

This file isn't supposed to be in the repo, right?

For the deployment onto the `gh-pages` branch, the content of this file gets packed into the bundle anyway, so it shouldn't be needed here I think.

2019-01-08 14:44 UTC, thibmeu approved these changes
Looks good.

2019-01-08 14:44 UTC, merged